apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: keycloak

resources:
  - kubernetes/keycloaks.k8s.keycloak.org-v1.yml
  - kubernetes/keycloakrealmimports.k8s.keycloak.org-v1.yml
  - kubernetes/kubernetes.yml

# patchesStrategicMerge
patches:
  - kubernetes/minikube.yml
